Phase9
Star-Academy/Team5-Codes pull request #9
Opened 2020-08-31 08:20 UTC by FarshidNooshi

close https://github.com/Star-Academy/codestar-intern-issues/issues/86

2020-09-01 07:51 UTC, mohammadhheidarzade approved these changes
خسته نباشید
چیزی به نظرم نیومد
صرفا توی اکشنتون بهتر بود ریسپانس رو چک کنید که آیا خطایی داره یا نه که بخواین خطاش رو هندل کنید

2020-09-01 12:40 UTC, soleyman79 approved these changes

2020-09-01 14:47 UTC, mhgheisarieh approved these changes

2020-09-04 20:23 UTC, mostmand requested changes

2020-09-04 20:23 UTC, mostmand commented on C#/Phase9_API/Phase9_API.Test/TestResponse.cs
> +        readonly bool[] forThrow = { false, false, false, false };
کد این کلاس اصلا گویا نیست به ویژه این آرایه‌ی forThrow

2020-09-04 20:23 UTC, mostmand commented on C#/Phase9_API/Phase9_API/Controllers/MainController.cs
> +            var items = App.ReadItemsFromFile<Person>();
در اینجا
items
چیست؟
چرا تابع
App.ReadItemsFromFile<Person>()
صدا زده می‌شود؟ مگر این
Api
قرار نیست تنها یک جستجو روی الستیک انجام دهد پس خواندن از فایل به چه منظور است؟

2020-09-04 20:23 UTC, mostmand commented on C#/Phase9_API/Phase9_API/Controllers/MainController.cs
> +        public IActionResult Get([FromBody] string[] query)
نام این تابع گویا نیست از نامی که گویای جستجو کردن باشد استفاده کنید

2020-09-04 20:23 UTC, mostmand commented on C#/Phase9_API/Phase9_API/Controllers/MainController.cs
> +        private string TakeOutput(ISearchResponse<Person> response)
نام این تابع نیز گویا نیست
CreateOutput
یا 
CreateResponse
شاید بهتر باشد

2020-09-04 20:23 UTC, mostmand commented on C#/Phase9_API/Phase9_API/Phase9_API.csproj
> +    <ProjectReference Include="..\..\Phase8\Phase8.csproj" />
بهتر است به جای
ProjectReference
فاز 8 را یک نوگت کنید و به آن نوگت ارجاع دهید

2020-09-04 20:23 UTC, mostmand commented on C#/Phase9_API/Phase9_API/Controllers/MainController.cs
> +            var items = App.ReadItemsFromFile<Person>();
هم چنین به جای این که یک کلاس
App
با توابع
static
داشته باشید بهتر است یک اینترفیس که عمل جستجو را بر عهده دارد داشته باشید و در این کلاس با
DependencyInjection
از آن استفاده کنید

2020-09-05 05:40 UTC, soleyman79 commented on C#/Phase9_API/Phase9_API/Controllers/MainController.cs
> +        public IActionResult Get([FromBody] string[] query)
ممنون. اسمش رو تغییر دادیم

2020-09-05 05:42 UTC, soleyman79 commented on C#/Phase9_API/Phase9_API/Controllers/MainController.cs
> +        private string TakeOutput(ISearchResponse<Person> response)
مچکر. اینم تغییر دادیم

2020-09-05 06:23 UTC, FarshidNooshi commented on C#/Phase9_API/Phase9_API.Test/TestResponse.cs
> +        readonly bool[] forThrow = { false, false, false, false };
برای تست کردن اکسپشن یک ریسپانس دستی ساختیم و توی قسمت درست شدن ریسپانس، با این ارایه میگفتیم که کدام حالت از ولیدیتر تست بشود مثلا اگر خانه ی اول ارایه مقدارش 1 بشود ما حالت 
TerminatedEarly 
ریسپانس ترو میشود و باید منتظر پرتاب اکسپشن مربوطش بشیم.

2020-09-06 05:41 UTC, MahdiHma approved these changes
خداقوت! خیلی هم عالی

2020-09-06 08:31 UTC, mostmand commented on C#/Phase9_API/Phase9_API.Test/TestResponse.cs
> +        readonly bool[] forThrow = { false, false, false, false };
منظورم اینه که میشه این قسمت رو تمیزتر و گویاتر نوشت

2020-09-06 08:33 UTC, mostmand requested changes

2020-09-06 08:33 UTC, mostmand commented on C#/Phase9_API/Phase9_API/Controllers/MainController.cs
> +            var searchEngine = new Phase8.Nest.SearchEngine();
از
DependencyInjection
استفاده کنید به این صورت که
ISearchEngine
رو توی کانستراکتور این کلاس ورودی بگیرید و توی متد
ConfigureServices
کلاس
Startup
اون رو
inject
کنید

2020-09-06 09:47 UTC, mostmand approved these changes

2020-09-06 10:22 UTC, merged